### ISSUE TITLE
Datapixx free dual CLUT

### ISSUE THREAD

**Issue by jcbyts** [HukLab/PLDAPS#11]
Implement software based overlay pointer with dual color lookup table (CLUT) based on psychtoolbox's stereo display shader. 

See branch NewOverlay

**Comment by jcbyts** [comment]
@jonaskn  What is left to do before merging NewOverlay into OpenReception?

**Comment by jonaskn** [comment]
how about this:requesting the overlay is part of the screen opening process anyways already and you had to change it to implement the new overlay. so move the creation there, but leave the cluts empty for now, but assign the overlayPointer for datapixx or software overlay.
We then assign the colors later (in datapixx.init or similar). 
If easy, have a updateOverlayCLUTs function that will be called from datapixx.init, but could also be called during experiments if needed.

**Comment by jcbyts** [comment]
Merged with openreception. TODO: updateOverlayCLUTS , which might be better thought of as a part of the separate colorIndexing issue
