### ISSUE TITLE
Assign unique_number_time in trialSetup instead of trialPrepare

### ISSUE THREAD

**Issue by jonaskn** [HukLab/PLDAPS#20]
To sync to other devices we currently mostly use datapixx with 16 bits strobed, where the first 8 bits are used to send data and the second 8 bits can carry specific flags for events.

Main synchronization is via a unique_number_time we send as a sequence of 6 values as data (first 8 bits) before each trial. 
We can later identify the times when these were sent in PLDAPS and received in the other devices and make e.g. a linear regression to synchronize the clocks.

If we do not have datapixx, we could send via parallel port or other devices, but unique_number_time in not assigned until trialPrepare in pldapsDefaultTrialFunction. As you typically do not want any time consuming operations after after trialPrepare was run, assignment of unique_number_time could be moved to trialSetup. 

This should be backwards compatible.

currently the value is stored at p.trial.datapixx.unique_number_time
One could also consider moving it to p.trial.pldaps.unique_number_time, but for consistency, we would have to keep it duplicated at p.trial.datapixx.unique_number_time

**Comment by czuba** [comment]
outdated
