### ISSUE TITLE
PLDAPS in octave

### ISSUE THREAD

**Issue by lpl1977** [HukLab/PLDAPS#22]
Has anyone tried running PLDAPS under octave?

**Comment by czuba** [comment]
Not that I'm aware of.  You're welcome to try, and it might 'just work'. ...if it does, let us know.

One major caveat though:  We don't currently have any need/interest in developing specific octave compatibility (or even a machine with Octave running here in Austin), so venturing down that path would most likely be akin to 'undocking from the PLDAPS mothership'.

**Comment by lpl1977** [comment]
There are some syntax differences that prevent it from working out of the box.

I'm going to port a version of pldaps over to GNU octave.  I think this is probably the wave of the future given that octave is free and that psychophysics toolbox runs under octave.  Single board computers like Raspberry Pi run octave and are very easy to use with psychophysics toolbox.  Plus, single board computers such as 
https://www.inforcecomputing.com/products/single-board-computers-sbc/qualcomm-snapdragon-805-inforce-6540-sbc
are getting to the point that they can support research grade graphics.
