### ISSUE TITLE
pathtopldaps in openScreen.m (software overlay) not conform with Ubuntu

### ISSUE THREAD

**Issue by ollimuh** [HukLab/PLDAPS#25]
Not sure what works on Mac/Windows.
Changed lines 288,298 to

pathtopldaps=fileparts(which('pldaps.m'));
p.trial.display.shader = LoadGLSLProgramFromFiles(fullfile(pathtopldaps, '..', 'SupportFunctions', 'Utils', 'overlay_shader.frag'), 2, icmShaders);

to get rid of a file not found error on Ubuntu.

**Comment by czuba** [comment]
Huh, good catch. Thanks!  ...just pushed an updat to use the auto-generated pldaps root directory path from:
`p.trial.pldaps.dirs.proot`
