### ISSUE TITLE
Feature request: Helper function for modifying conditions during pause

### ISSUE THREAD

**Issue by jcbyts** [HukLab/PLDAPS#3]
from chat with Jonas:

as to changing during pause:
when you change something in p.trial while in pause or during the afterTrial state, this will be added to the new defaults for all future trials, but will not overrule anything in the conditions structs (as that is difficult to know, what is wanted). If you want something to change that is defined in a condition, you have to change all future condition structs. If we had a condition naming convertion (a field called Nr, e.g.) we could build a helper fucntion for that

**Comment by czuba** [comment]
...conditions struct is outdated
